//
//  RandomImageInteractor.swift
//  randomdogios
//
//  Created by Komkrit Kunanusont on 20/2/2565 BE.
//  Copyright (c) 2565 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RandomImageBusinessLogic
{
  func doSomething(request: RandomImage.RandomDogImage.Request)
}

protocol RandomImageDataStore
{
  //var name: String { get set }
}

class RandomImageInteractor: RandomImageBusinessLogic, RandomImageDataStore
{
  var presenter: RandomImagePresentationLogic?
  var worker: RandomImageWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: RandomImage.RandomDogImage.Request)
  {
    worker = RandomImageWorker()
//    worker?.getRandomImage()
    
//    let response = RandomImage.RandomDogImage.Response()
//    presenter?.presentSomething(response: response)
  }
}
