//
//  RandomImageWorker.swift
//  randomdogios
//
//  Created by Komkrit Kunanusont on 20/2/2565 BE.
//  Copyright (c) 2565 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class RandomImageWorker
{
    var apiService: DogCeoApiService?
    func getRandomImage(number: Int) async -> RandomImageWorkerResponse {
        do{
        let workerResponse: RandomImageWorkerResponse = try await withCheckedThrowingContinuation({ continuation in
            apiService?.getRandomImage(number: number, completion: { response in
                continuation.resume(returning: response)
            })
        })
        return workerResponse
        } catch {
            return RandomImageWorkerResponse(message: nil, status: "failed")
        }
    }
}

struct RandomImageWorkerResponse: Codable {
    let message: [String]?
    let status: String?
}
//
//{
//    "message": [
//        "https://images.dog.ceo/breeds/akita/An_Akita_Inu_resting.jpg",
//        "https://images.dog.ceo/breeds/dalmatian/cooper2.jpg",
//        "https://images.dog.ceo/breeds/terrier-norwich/n02094258_866.jpg"
//    ],
//    "status": "success"
//}
