//
//  RandomImagePresenter.swift
//  randomdogios
//
//  Created by Komkrit Kunanusont on 20/2/2565 BE.
//  Copyright (c) 2565 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RandomImagePresentationLogic
{
  func presentSomething(response: RandomImage.RandomDogImage.Response)
}

class RandomImagePresenter: RandomImagePresentationLogic
{
  weak var viewController: RandomImageDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: RandomImage.RandomDogImage.Response)
  {
//    let viewModel = RandomImage.RandomDogImage.ViewModel()
//    viewController?.displaySomething(viewModel: viewModel)
  }
}
