//
//  RandomImageModels.swift
//  randomdogios
//
//  Created by Komkrit Kunanusont on 20/2/2565 BE.
//  Copyright (c) 2565 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum RandomImage
{
  // MARK: Use cases
  
  enum RandomDogImage
  {
    struct Request {
        var number: Int = 1
    }
      struct Response {
          let value: [DogImage]?
          
      }
      struct ViewModel {
          let value: [String]?
          let errorMessage: String?
      }
  }
}

struct DogImage {
    let url: String
}
